# Generated by Django 2.1.3 on 2018-12-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('vin', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField()),
                ('disposal_date', models.DateTimeField()),
                ('passport', models.ImageField(upload_to='passports')),
            ],
        ),
    ]
